### ISSUE TITLE
Add Supervisor Access to Leaves Page and Update Leave Status Form

### ISSUE THREAD

**Issue by Dark-Developer93** [Dark-Developer93/LeaveTracker#8]
## Description

Implement a feature that allows supervisors to access the Leaves page and update leave statuses for their supervisees. This includes creating a new route for supervisors, updating the sidebar to display this option for users with supervisor roles, and adding a new SUPERVISOR role to the schema.

## Tasks

1. Update the schema to include a new SUPERVISOR role.
2. Create a new route for supervisors to access the Leaves page.
3. Update the @SideBar.tsx component to include the new supervisor route.
4. Modify the Leaves page to be accessible by supervisors.
5. Update the Update Leave Status form to be visible and functional for supervisors.
6. Implement access control to ensure only supervisors can see and interact with their supervisees' leave requests.
7. Add filtering functionality to show only the leave requests of the supervisor's supervisees.

## Acceptance Criteria

- [ ] The schema includes a new SUPERVISOR role.
- [ ] A new route for supervisors to access the Leaves page is created.
- [ ] The sidebar in @SideBar.tsx displays the Leaves option for users who are supervisors.
- [ ] Supervisors can access the Leaves page and view leave requests of their supervisees.
- [ ] The Update Leave Status form is visible and functional for supervisors on the Leaves page.
- [ ] Supervisors can only view and update leave statuses for their supervisees.
- [ ] The Leaves page for supervisors includes filtering to show only their supervisees' requests.

## Implementation Details

1. Update schema.prisma:

```prisma
// prisma/schema.prisma
enum Role {
USER
ADMIN
MODERATOR
SUPERVISOR
}
```

2. Update Routes.ts:

```typescript
// components/Common/Routes.ts
// ... existing routes ...
export const SupervisorRoutes = [
  // ... other routes same as the UserRoutes ...
  {
    name: "Leaves",
    href: "/supervisor/leaves",
    icon: CalendarIcon,
  },
];
```

3. Update @SideBar.tsx:

```typescript
// components/Common/SideBar.tsx
// ... existing imports ...
import {
  AdminRoutes,
  ModeratorRoutes,
  UserRoutes,
  SupervisorRoutes,
} from "./Routes";
// ... existing code ...
const SideBar = ({ user }: SideBarProps) => {
  // ... existing code ...
  const supervisorIconsRouter = () => {
    return <>{RenderIconsRoutes({ routes: SupervisorRoutes })}</>;
  };
  return (
    // ... existing JSX ...
    <nav className="flex flex-col items-center px-3 overflow-y-auto">
      {user?.role === "ADMIN" && adminIconsRouter()}
      {user?.role === "USER" && userIconsRouter()}
      {user?.role === "MODERATOR" && moderatorIconsRouter()}
      {user?.role === "SUPERVISOR" && supervisorIconsRouter()}
    </nav>
    // ... rest of the JSX ...
  );
};
```

## Additional Notes

- Ensure that users with the SUPERVISOR role are properly identified in the system.
- Consider adding a notification system for supervisors when new leave requests are submitted.
- Update user documentation to reflect the new supervisor capabilities.
- Test thoroughly to ensure that supervisors can only access and modify leave requests for their own supervisees.
- Update any role-based access control logic throughout the application to accommodate the new SUPERVISOR role.
